In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

data= requests.get("https://www.bizbaya.com/sme-india/Maharashtra/Mumbai")
soup= BeautifulSoup (data.text, 'html.parser')
table = soup.find_all('div',{'class':'views-field views-field-company-name'})
sme=[]
for i in table:
    name=i.text
    url="https://www.bizbaya.com" + i.find('a').attrs['href']
    print(name,url)
    sme.append([name,url])

 1-Up Clothing Co., Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/1-Up-Clothing-Co
 3D Networks Pvt. Ltd., Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/3D-Networks-Pvt-Ltd
 A G Technologies Pvt Ltd, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/A-G-Technologies-Pvt-Ltd
 A L M Engineering & Instrumentation Pvt. Ltd, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/A-L-M-Engineering-Instrumentation-Pvt-Ltd
 A-1 Industries, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/A-1-Industries
 A. I. M. Exports, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/A-I-M-Exports
 A. K. Impex, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/A-K-Impex
 A. K. Motiwala Exports, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/A-K-Motiwala-Exports
 A. M. & Associates, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/A-M-Associates
 Aai International, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Aai-International
 Aakash Engineers, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Aakash-Engineers
 Aarya International, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Aarya-International
 Aasiya Exports, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Aasiya-Exports
 Aavran Exports (India), Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Aavran-Exports-India
 ABC Chemical Export Pvt. Ltd., Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/ABC-Chemical-Export-Pvt-Ltd
 ABG Shipyard Ltd., Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/ABG-Shipyard-Ltd
 Abhishek Infotech Pvt Ltd, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Abhishek-Infotech-Pvt-Ltd
 ABM Architects Pvt. Ltd, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/ABM-Architects-Pvt-Ltd
 ABN AMRO Central Enterprise Services Pvt Ltd, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/ABN-AMRO-Central-Enterprise-Services-Pvt-Ltd
 Abu Dhabi Commercial Bank Ltd., Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Abu-Dhabi-Commercial-Bank-Ltd
 Accutrol Systems Pvt. Ltd., Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Accutrol-Systems-Pvt-Ltd
 Aces Enterprises, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Aces-Enterprises
 Acharya Exports, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Acharya-Exports
 Acme Mechinery Co., Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Acme-Mechinery-Co
 Acrysil (India) Ltd., Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Acrysil-India-Ltd
 Adaqi Infra Pvt. Ltd., Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Adaqi-Infra-Pvt-Ltd
 Adarsh Infrainterio P.Ltd, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Adarsh-Infrainterio-P-Ltd
 Adil Arts, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Adil-Arts
 Aditya Industries, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Aditya-Industries
 Aditya Jyot Eye Hospital Pvt. Ltd., Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Aditya-Jyot-Eye-Hospital-Pvt-Ltd
 Ador Welding Limited, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Ador-Welding-Limited
 Advance GRP Cooling Towers Pvt.Ltd., Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Advance-GRP-Cooling-Towers-Pvt-Ltd
 Adventity BPO India Pvt Ltd, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Adventity-BPO-India-Pvt-Ltd
 Aegis Tech Ltd, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Aegis-Tech-Ltd
 Aeroquip Cooling Systems, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Aeroquip-Cooling-Systems
 Affarsstrategerna Think Tech Technologies Pvt Ltd, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Affarsstrategerna-Think-Tech-Technologies-Pvt-Ltd
 Agarwal Engineering Corportion, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Agarwal-Engineering-Corportion
 Agricon Industries, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Agricon-Industries
 Ahad International, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Ahad-International
 AIC Overseas Pvt. Ltd, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/AIC-Overseas-Pvt-Ltd
 Aimco Pesticides Ltd., Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Aimco-Pesticides-Ltd
 Airpac Exprots, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Airpac-Exprots
 Aishwarya Tools & Dies, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Aishwarya-Tools-Dies
 Ajanta Marbles Pvt. Ltd., Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Ajanta-Marbles-Pvt-Ltd
 Ajanta Pharma Limited, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Ajanta-Pharma-Limited
 Ajeets Management Contracting & Consultancy Pvt. Ltd, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Ajeets-Management-Contracting-Consultancy-Pvt-Ltd
 Ajmal Fragrances & Fashions Pvt. Ltd., Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Ajmal-Fragrances-Fashions-Pvt-Ltd
 Ajosha Bioteknik P. Ltd., Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Ajosha-Bioteknik-P-Ltd
 Akay Industries Pvt. Ltd, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Akay-Industries-Pvt-Ltd
 Al - Awwal Garments, Mumbai, Maharashtra, Mumbai, Maharashtra  https://www.bizbaya.com/sme-india/Maharashtra/Mumbai/Al-Awwal-Garments

In [ ]:
import pandas as pd
sme=pd.DataFrame(sme, columns=["Name","URL"])
sme

In [24]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
header = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36'}

data= requests.get("https://www.naukri.com/data-science-jobs", headers=header)
soup= BeautifulSoup (data.text, 'html.parser')
table = soup.find_all('div',{'class':'row'})
jobs=pd.DataFrame(columns=["Job Title","Location","Company Name","Experience Required","Skills Required","Job Description"])
#table

for i in table:
    try:
        title=i.find('a').text
    except:
        title="NA"
    try:
        loc=i.find(class_="loc").text
    except:
        loc="NA"
    try:
        exp=i.find(class_="exp").text
    except:
        exp="NA"
    try:
        org=i.find(class_="org").text
    except:
        org="NA"
    try:
        skill=i.find(class_="skill").text
    except:
        skill="NA"
    try:
        desc=i.find(class_="desc").text
    except:
        desc="NA"
    jobs=jobs.append({"Job Title":title,"Location":loc,"Company Name":org,"Experience Required":exp,"Skills Required":skill,"Job Description":desc}, ignore_index=True)

In [27]:
jobs.head(10)

,Job Title,Location,Company Name,Experience Required,Skills Required,Job Description
0,NA,NA,NA,NA,NA,NA
1,Chief Intelligence Officer - Data Science & An...,"Delhi NCR, Mumbai, Bengaluru, Gurgaon",TalPro,8-12 yrs,"Machine Learning, Chief Intelligence Officer, ...","Machine Learning, Chief Intelligence Officer,..."
2,Director - Data Science - B2B Product Setup,"Delhi, Pune",CareerNet Consulting,10-15 yrs,"Data Science, Machine Learning, data security,...","Data Science, Machine Learning, data security..."
3,Director - Data Science - Product Setup,Delhi,CareerNet Consulting,9-14 yrs,"Data Science, Machine Learning, Product Manage...","Data Science, Machine Learning, Product Manag..."
4,Data Scientist/ Data Science - KPO - IIT/ NIT/...,Bengaluru,Superior Group,4-6 yrs,"Deep Learning, Machine Learning, Data Science,...","Deep Learning, Machine Learning, Data Science..."
5,Data Engineer - Analytics & Data Science Platform,Bengaluru,BuzzHire,2-7 yrs,"data warehousing, business intelligence, big d...","data warehousing, business intelligence, big ..."
6,Engineering Manager (Web Technologies/ Data Sc...,Bengaluru,Collins Aerospace (Rockwell Collins),8-13 yrs,"python, engineering management, project manage...","python, engineering management, project manag..."
7,Data Science Developer - Analytics/ Alteryx,Mumbai,The Hiring Story,3-7 yrs,"SQL Database, R, Analytics, Macros, Time Serie...","SQL Database, R, Analytics, Macros, Time Seri..."
8,Opening for Data Science Architect (AI Archite...,Greater Noida,Techs to Suit Inc,9-14 yrs,"Deep Learning, Natural Language Processing, Ma...","Deep Learning, Natural Language Processing, M..."
9,"Internship - Artificial Intelligence, Machine ...",India,Xen.ai,0-2 yrs,"Machine Learning, Data Science, Artificial Int...","Machine Learning, Data Science, Artificial In..."